### ISSUE TITLE
Hosting service and Media service for our Club Gamma website as well as mobile app. 

### ISSUE THREAD

**Issue by chirayu-joshi** [clubgamma/clubgamma.github.io#2]
Hello folks, as we are approaching towards creation of web app and mobile app, we will require to host it on a secure, cost efficient, well known and reliable host provider. 

### For WebApp:
Considering future requirements i.e dynamic website, we will require servers to run our backend services. We will also be requiring to save images, videos, files, data into database,  etc. Also our backend language may vary according to situation later. We should easily be able to create APIs and run services like compression of images, etc from our backend. 

### For Mobile App:
Instead of storing images into mobile app, we can store images into backend server and then fetch from our mobile app when user opens it. Those images include images of blogs, events, etc. Using common storage between web and mobile app will help us to synchronise content like blogs and events. They can be cached once loaded to save bandwidth. 

### List of cloud providers and host providers:

**Cloud Service Providers**
1. [AWS](https://aws.amazon.com/free/)
2. [Google Cloud](https://cloud.google.com/pricing/list)

**Hosting service providers**
1. [Hostinger](https://www.hostinger.in/web-hosting#comparison)
2. [Bluehost](https://www.bluehost.in/hosting/shared)
3. [Hostgator](https://www.hostgator.in/web-hosting/linux-shared-hosting)
and many more...

### My preference:

**AWS Free Tier**
_[AWS Free Tier](https://aws.amazon.com/free/)_ includes services like computation, block level storage, static storage, database storage, CDNs, SNS services, resource utilization analytics, and many more services. All these services for free for 1 year. It also provides domain name registration but it is paid one. 

**What after 1 year?**
AWS is slightly costly as compared to web hosting services IF we use on-demand pricing plan. In on-demand pricing plan, we pay only for the resources used. We can discontinue usage, and stop paying in a minute. But in reservation plan, we can't do so. To overcome this issue, we can analyse usage of 1 year, and buy necessary resources in reservation plan. 

If you find any other better service, please do suggest.

**Comment by jayskhatri** [comment]
Hey @chirayu-joshi, let me know that until our first event, will this clubgamma.github.io (GitHub Page for our site) work or not?

**Comment by chirayu-joshi** [comment]
I will try to finish our basic static site until tomorrow (13 August). And then we will host our static site as GitHub Page. 

I have hosted a React site on GitHub previously. So I think that there will not be any issue while hosting this site too.

**Comment by jayskhatri** [comment]
> 
> 
> I will try to finish our basic static site until tomorrow (13 August). And then we will host our static site as GitHub Page.
> 
> I have hosted a React site on GitHub previously. So I think that there will not be any issue while hosting this site too.

Okay 👍
