### ISSUE TITLE
GitHub Page is not available.

### ISSUE THREAD

**Issue by chirayu-joshi** [clubgamma/clubgamma.github.io#5]
# GitHub Page is not available :lock:

**As we decided to host our initial static site on GitHub, I tried to host out demo site on GitHub Page.**

But I found no settings option :gear:. I checked my personal private repo settings, and I found that I can host my static React site even if it is private. 

## Possible reasons:

- I might not have necessary permissions.
- This feature is missing for our organisation.

**Comment by jayskhatri** [comment]
Hey @chirayu-joshi can you check one thing, I guess we have to put the client folder's all the files in the root of repo. Otherwise site won't get host.

**Comment by chirayu-joshi** [comment]
Okay @jayskhatri , we can make our repo public. 

Until we buy our domain name, can you register for our free domain having .ml, .tk, .ga, .cf, .gq as TLD? You can register for free on [Freenom](https://www.freenom.com/). We will decide later on where we actually host our website, but can you register all of them for now?

Also AWS S3 provides static web hosting service for nearly free. AWS S3 charges on the basis of storage used and data transfer. Our site will be of less than 5 MB including all assets and it won't get 50K views initially. So we can host it for 0-5 rupees per month. And if we apply for free tier, it would be free.

**Comment by rudrabarad** [comment]
As far as I know, it will only work if there is **index.html** file as it doesn't read anything else other than that

![Capture1](https://user-images.githubusercontent.com/53337681/89181720-e4a27080-d5b1-11ea-92d8-1044750d760b.PNG)

**Comment by jayskhatri** [comment]
@chirayu-joshi I got this error, maybe issue is from their side. Do you have any idea? because it is not showing anything in **My domain**.

![image](https://user-images.githubusercontent.com/38436564/89193239-57681780-d5c3-11ea-9c1f-47bf5a7a9899.png)

**Comment by shubhamdraval** [comment]
@jayskhatri Freenom is not working. It's showing the same error since one year.
