### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by Suvoo** [clubgamma/clubgamma.github.io#8]
I would like to update the websites screenshots to the readme file

**Comment by jayskhatri** [comment]
Thanks @Suvoo , for showing enthusiasm to work 👏

If you want to contribute we have some projects on our organization

For more information of projects [visit our website](https://clubgamma.github.io/hacktoberfest/) also you can join the [discord channel of club gamma](https://discord.gg/kjnp6wU)
